import Head from 'next/head';
import Image from 'next/image';
import Center from '../components/Center';
import NavBar from '../components/NavBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bank Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Center titulo='Bank Site' mensagem='Bank Project! O banco feito para você!' />
    </div>
  );
}
