import Head from 'next/head';
import Image from 'next/image';
import Center from '../components/Center';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bank Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center titulo='Teste' mensagem='Site do banco Site do banco Site do banco' />
    </div>
  );
}
