import Head from 'next/head';
import Nav from '../components/NavBar/NavBar';
import Footer from '../components/Footer/Footer';

export default function Home() {
  return (
    <div className='bg-black'>
      <Head>
        <title>Bank Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <div className="flex items-center justify-center h-screen mb-12 bg-fixed bg-cover custom-img">
        <div className="top-0 left-0 right-0 bottom-0 z-[2] custom-img z-2"/>
        <div className="absolute p-5 text-white z-[2]  mt-[-10rem]">
        </div>
    </div>
      <Footer />
    </div>
  );
}
